CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    encrypted_email VARCHAR(1000) NOT NULL,
    email_hash VARCHAR(64) NOT NULL,
    purpose VARCHAR(80) NOT NULL,
    notice_version VARCHAR(80) NOT NULL,
    source VARCHAR(160) NOT NULL,
    requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
    token_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    confirmation_hash VARCHAR(64) UNIQUE,
    withdrawal_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING','CONFIRMED','WITHDRAWN')),
    confirmed_at TIMESTAMP WITH TIME ZONE,
    withdrawn_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(email_hash,purpose)
);
CREATE INDEX consent_audience ON subscription(purpose,status);
CREATE TABLE consent_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT NOT NULL REFERENCES subscription(id),
    action VARCHAR(255) NOT NULL,
    actor VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE campaign (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    purpose VARCHAR(80) NOT NULL
);
